version: "3.8"

services:
  pangolin-ip-rule-manager:
    # Build the image from the local Dockerfile (recommended for local use)
    build: .
    # Also tag the image name so Portainer/Compose show a friendly name
    image: pangolin-ip-rule-manager:latest
    container_name: pangolin-ip-rule-manager

    # Optional: load environment overrides from a local file next to this compose file
    # Create a file named `config.env` and put your sensitive/override values there.
    # Example content:
    #   PANGOLIN_TOKEN=REPLACE_ME
    #   RESOURCE_IDS=2,7,12
    #   RETENTION_MINUTES=10080
    env_file:
      - ./config.env

    environment:
      # Defaults (can be overridden by env_file or Portainer UI)
      PANGOLIN_URL: https://api.url.of.your.pangolin.instance
      RESOURCE_IDS: "2,7,12" # comma-separated list of resource IDs to be updated. Run the container once to see the list of available resource IDs.
      ORG_ID: your_org_id # your organization ID in pangolin
      # TODO: securely store this in a secret and not as an environment variable
      PANGOLIN_TOKEN: your_pangolin_api_token # see pangolin-api-key-permissions.png for needed permissions

      RETENTION_MINUTES: "1440"   # IP's will stay for 1440 minutes = 1 day in the allowlist after their last call
      CLEANUP_INTERVAL_MINUTES: "60"   # how often to clean up the state file with expired IP's'

      # no need to adapt these for now
      LISTEN_PORT: "8080"
      STATE_FILE: /data/state.json   # store state inside a dedicated data volume
      RULE_PRIORITY: "0"

    # Persist only the state file. The application code stays inside the image.
    volumes:
      - pangolin-ip-rule-manager-data:/data

    restart: unless-stopped

volumes:
  pangolin-ip-rule-manager-data: {}
