services:
  pangolin-ip-rule-manager:
    # Build the image from the local Dockerfile (recommended for local use)
    build: .
    # Also tag the image name so Portainer/Compose show a friendly name
    image: pangolin-ip-rule-manager:latest
    container_name: pangolin-ip-rule-manager

    # Optional: load environment overrides from a local file next to this compose file
    # Create a file named `config.env` and put your sensitive/override values there.
    # Example content:
    #   PANGOLIN_TOKEN=REPLACE_ME
    #   RESOURCE_IDS=2,7,12
    #   RETENTION_MINUTES=10080
    env_file:
      - ./config.env

    environment:
      # no need to adapt these for now
      LISTEN_PORT: "8080"
      STATE_FILE: /data/state.json   # store state inside a dedicated data volume
      RULE_PRIORITY: "0"

    networks:
      - pangolin # put in pangolin network

    # Persist only the state file. The application code stays inside the image.
    volumes:
      - pangolin-ip-rule-manager-data:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro # comment out if crowdsec integration is not needed

    restart: unless-stopped

volumes:
  pangolin-ip-rule-manager-data: {}

networks:
  pangolin:
    external: true